name: testproject_with_qr_ble
description: testproject_with_qr_ble

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  qr_flutter: ^3.1.0
  permission_handler: ^5.1.0
  equatable: 1.2.6
  flutter_bloc:
  flutter_blue: 0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true